### ISSUE TITLE
Can't return static local variable, after newlib was removed

### ISSUE THREAD

**Issue by copyrat90** [GValiente/butano#53]
# Issue
If you return a static local variable, link fails with undefined reference to `__cxa_guard_acquire`, `__cxa_guard_release`.
(I also got undefined reference to `atexit` in my real code.)

This doesn't happen before 23f4ba2 (newlib removed).

# Reproduce

## Code

```cpp
class Singleton {
public:
    static auto instance() -> Singleton& {
        static Singleton inst;
        return inst;
    }
private:
    Singleton() {}
};

int main() {
    Singleton::instance();
}
```

## Result
```cpp
Linking ROM...
.../arm-none-eabi/bin/ld.exe: main.o: in function `Singleton::instance()':
/test/src/main.cpp:6: undefined reference to `__cxa_guard_acquire'
.../arm-none-eabi/bin/ld.exe: /test/src/main.cpp:4: undefined reference to `__cxa_guard_release'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [/butano/butano.mak:69: /test/test.elf] Error 1
make[1]: *** [/butano/butano.mak:202: build] Error 2
make: *** [/butano/butano.mak:197: all] Error 2
```

**Comment by GValiente** [comment]
https://github.com/GValiente/butano/commit/c39fbb395b8d0672b540a86994d33398f7686a4a should fix it.

**Comment by copyrat90** [comment]
I'm still getting an undefined reference to `atexit` after updating, for this snippet

```cpp
#include <bn_best_fit_allocator.h>

class MyHeap
{
public:
    static auto instance() -> MyHeap& {
        static MyHeap taskHeap;
        return taskHeap;
    }
private:
    MyHeap() : _alloc(_mem, sizeof(_mem)) { }
private:
    uint8_t _mem[8192];
    bn::best_fit_allocator _alloc;
};

int main() {
    MyHeap::instance();
}
```

**Comment by GValiente** [comment]
https://github.com/GValiente/butano/commit/5ab8d2b23b2e70b27472de45ed073ba077aadfed should fix it.

By the way, a Butano program should never return from `main()`:

````cpp
#include <bn_core.h>
#include <bn_best_fit_allocator.h>

class MyHeap
{
public:
    static auto instance() -> MyHeap& {
        // BN_DATA_EWRAM omitted, as it wasn't the issue
        static MyHeap myHeap;
        return myHeap;
    }
private:
    MyHeap() : _alloc(_mem, sizeof(_mem)) { }
private:
    uint8_t _mem[8192];
    bn::best_fit_allocator _alloc;
};

int main() {
    bn::core::init();

    MyHeap::instance();

    while(true)
    {
        bn::core::update();
    }
}
```

**Comment by copyrat90** [comment]
It is fixed now, thanks.

I know you shouldn't return from `main()`, but this snippet is meant to show the build error, so I omitted those for shorter snippet.
I'll just include the main game loop next time.
